### ISSUE TITLE
Custom event type not present in GTM

### ISSUE THREAD

**Issue by theycallmeswift** [reddit/reddit-gtm-template#15]
Hey, folks --

I'm try to setup a custom event type in Google Tag Manager for the Reddit pixel, but I'm not seeing the option in the dropdown list, despite seeing it available in the source here. I have already tried a full uninstall/reinstall of the template. Can you check to see if there was an issue with the release? 

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/434373/156798715-7b7b4ce4-16ca-4d78-9691-17d9b6842b67.png">

**Comment by theycallmeswift** [comment]
@woodchuckgym glad you were able to catch that issue. FYI that I'm still not seeing the Custom event option in the template. 

The freshly installed template is showing version "0a115", which is the prefix of the hash that was present in the previous commit. Not sure if y'all need to do something specific to deploy it or if there's a delay in propogation. Will check back later today!

<img width="942" alt="image" src="https://user-images.githubusercontent.com/434373/156836206-eb4ae60f-7336-4ca4-b36d-7490805e0bb6.png">

**Comment by woodchuckgym** [comment]
Heya.  Thanks again for catching this!

When the metadata.yaml is updated, it takes teh Google a few hours to update the template in the gallery.  I tried it myself a few moments ago, and I can confirm it has now been updated.

Could you give it one more try?

**Comment by theycallmeswift** [comment]
@woodchuckgym it's working now! Thank you so much!
