### ISSUE TITLE
PageVisit doesn't work correctly

### ISSUE THREAD

**Issue by flippidippi** [reddit/reddit-gtm-template#27]
It seems like the template is adding variables that shouldn't be there for PageView event

![image](https://github.com/reddit/reddit-gtm-template/assets/1396568/04a6fa79-ebfd-4d5e-92b8-131def97ab23)

**Comment by woodchuckgym** [comment]
TY for letting us know!  We'll look into it.

**Comment by peanutbutterduo** [comment]
@flippidippi Would you be able to provide a link to the page that this is occurring on? I can help take a look. Thanks!

**Comment by flippidippi** [comment]
It seems like the issue may have been that the manual reddit install also being on the page at the same time. When I removed the manual script include it seems to work now 🤷‍♂️ Sorry about that!
